In [1]:
import numpy as np

arr = np.arange(1, 101)

arr_reshaped = arr.reshape(10, 10)

row_sums = np.sum(arr_reshaped, axis=1)

max_sum_row = np.argmax(row_sums)

print("Array:")
print(arr_reshaped)
print()
print("Row Sums:")
print(row_sums)
print()
print("Row with Maximum Sum:", max_sum_row)


Array:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Row Sums:
[ 55 155 255 355 455 555 655 755 855 955]

Row with Maximum Sum: 9


In [2]:
import numpy as np


arr = np.arange(1, 101)

arr_reshaped = arr.reshape(10, 10)


row_sums = np.sum(arr_reshaped, axis=1)


max_sum_row = np.argmax(row_sums)

print("Array:")
print(arr_reshaped)
print()
print("Row Sums:")
print(row_sums)
print()
print("Row with Maximum Sum:", max_sum_row)


Array:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Row Sums:
[ 55 155 255 355 455 555 655 755 855 955]

Row with Maximum Sum: 9
